### ISSUE TITLE
Error: gm not found, make sure GraphicsMagick is installed and gm is available in your environment. spawn gm ENOENT

### ISSUE THREAD

**Issue by ycpatel813** [timkuijsten/node-thumbnail#5]
Got error when using module to create thumbnil from image.

**Comment by timkuijsten** [comment]
then node can't find the gm executable. if you type `whereis gm` or `locate gm` what does it give you? Try to find the `gm` executable on your system and make sure it's in the PATH environment variable of your node process.

**Comment by ycpatel813** [comment]
set PATH and its working now.
Thank you.
